[en]
title = "Meska"
languageName = "English"
weight = 1
languagedir = "ltr"
contentdir = "content/en"

[ar]
title = "المدونة العربية"
languageName = "Arabic"
weight = 2
languagedir = "rtl"
contentdir = "content/ar"
