[[main]]
identifier = "about"
name = "About"
url = "about"
weight = 1

[[main]]
identifier = "writeups"
name = "Writeups"
url = "writeups"
weight = 2

[[main]]
identifier = "gallery"
name = "Gallery"
url = "gallery"
weight = 3
